# This is a basic workflow to help you get started with Actions

name: first flow
on: workflow_dispatch
jobs:
  Copy-Downloadble:
    runs-on: "ubuntu-latest"
    steps:
      - name: Hello
        run: echo "Hello World"
      - name: Good bye
        run : echo "good bye!"
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to storage using CLI
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            ls
              # show azure account being used
            az account show
