# This is a basic workflow to help you get started with Actions

name: RPA
on: workflow_dispatch
jobs:
  Copy-Downloadble:
    runs-on: "ubuntu-latest"
    steps:
      - name: Run inline script
        run: echo "Hello World"
