# This is a basic workflow to help you get started with Actions

name: first flow
on: workflow_dispatch
jobs:
  Copy-Downloadble:
    runs-on: "ubuntu-latest"
    steps:
      - name: Hello
        run: echo "Hello World"
      - name: Good bye
        run : echo "good bye!"
      - name: downloadable
        run: curl https://7-zip.org/a/7z2201-x64.exe --output 7z2201-x64.exe
